# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b19bfe00c01500d8ee46a50a2d65f300bd7ec1828a4c911c3c58f4e4389fcebc4f697e44193f329adce6900015bd2af05c85aa9a5f3e51b347ddf78cf4d42db1

test:
  secret_key_base: ebc331f356d9464aca34e252c26c159a694570e9a11aa4640fe5f74953e24235566f3707d7a8d7a0fe2c381b60d82c5e26b978ff03ff1e2cd4e066c64ee69de0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
